application/AGED/urls.py
#
# AGED/urls.py
#
# Author: Mihai Ionut Deaconu
#

from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls), # Admin interface
    path('accounts/', include('allauth.urls')), # Necessary for login, logout, signup etc.
    path('', include('core.urls')),
    path('media/count_data/<pk>/<name>', login_required(views.download)),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

application/core/urls.py
# 
# core/urls.py
#
# Author: Mihai Ionut Deaconu
#

from django.conf.urls import include
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [

    path('', login_required(views.index), name='index'),
    path('libraries/', login_required(views.libraries), name='libraries'),
    path('models/', login_required(views.models), name='models'),

    path('models/svm/', login_required(views.SVMModelListView.as_view()), name='svm_models'),
    path('models/svm/<model_name>', login_required(views.SVMModelDetailView.as_view()), name='svm_model_detail'),
    path('models/svm/<model_name>/genes', login_required(views.svm_genes), name='svm_genes'),
    
    path('models/rf/', login_required(views.RFModelListView.as_view()), name='rf_models'),
    path('models/rf/<model_name>', login_required(views.RFModelDetailView.as_view()), name='rf_model_detail'),
    path('models/rf/<model_name>/genes', login_required(views.rf_genes), name='rf_genes'),
    
    path('search/diseases', login_required(views.search_disease), name='search_disease'),
    path('search/studies', login_required(views.search_study), name='search_study'),
    path('search/samples', login_required(views.search_sample), name='search_sample'), 

    path('diseases/', login_required(views.DiseaseListView.as_view()), name='diseases'),
    path('diseases/create', login_required(views.DiseaseCreateView.as_view()), name='create_disease'),
    path('diseases/<abbreviation>', login_required(views.DiseaseDetailView.as_view()), name='disease_detail'),
    path('diseases/<abbreviation>/update', login_required(views.DiseaseUpdate.as_view()), name='disease_update'),
    path('diseases/<abbreviation>/confirm_delete', login_required(views.DiseaseDelete.as_view()), name='disease_delete'), 
    
    path('studies/', login_required(views.StudyListView.as_view()), name='studies'),
    path('studies/create', login_required(views.StudyCreateView.as_view()), name='create_study'),
    path('studies/<title>', login_required(views.StudyDetailView.as_view()), name='study_detail'),
    path('studies/<title>/update', login_required(views.StudyUpdate.as_view()), name='study_update'),
    path('studies/<title>/confirm_delete', login_required(views.StudyDelete.as_view()), name='study_delete'),

    path('studies/<title>/count_data/create', login_required(views.CountDataCreateView.as_view()), name='count_data_create'),
    path('studies/<title>/count_data/<name>', login_required(views.CountDataDetailView.as_view()), name='count_data_detail'),
    path('studies/<title>/count_data/<name>/update', login_required(views.CountDataUpdate.as_view()), name='count_data_update'),
    path('studies/<title>/count_data/<name>/confirm_delete', login_required(views.CountDataDelete.as_view()), name='count_data_delete'),  

    path('studies/<title>/count_data/<name>/samples', login_required(views.SampleListView.as_view()), name='samples'),
    path('studies/<title>/count_data/<name>/samples/import', login_required(views.import_sample), name='import_sample'),
    path('studies/<title>/count_data/<name>/samples/<sample_ID>', login_required(views.SampleDetailView.as_view()), name='sample_detail'),
]

application/core/models.py
# 
# core/models.py
#
# Author: Mihai Ionut Deaconu
#

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, FileExtensionValidator, RegexValidator
from django.urls import reverse

class Disease(models.Model):
  name = models.CharField(max_length=50, unique=True)
  abbreviation = models.CharField(max_length=6, unique=True)
  description = models.TextField()
  url = models.URLField(verbose_name = 'URL', blank=True)

  class Meta:
    verbose_name = 'Disease'
    verbose_name_plural = 'Diseases'
    ordering = ['name']
  def __str__(self):
    return "%s (%s)" % (self.name, self.abbreviation)
  def get_absolute_url(self):
    return reverse('disease_detail', args=[str(self.abbreviation)])

class Study(models.Model):
  DOI = models.CharField(max_length=50, unique=True,
                          validators=[RegexValidator(r'^doi:[0-9]{2}.[0-9]{4}\/[a-zA-Z0-9.]{0,40}$')], 
                          help_text='Please use format "doi:prefix/suffix"')
  title = models.CharField(max_length=200)
  url = models.URLField(verbose_name = 'URL', blank=True, null=True)
  publication_date = models.DateField(blank=True, null=True)
  journal = models.CharField(max_length=200, blank=True, null=True)

  class Meta:
    verbose_name = 'Study'
    verbose_name_plural = 'Studies'
    ordering = ['-publication_date']
  def __str__(self):
    return "%s %s" % (self.title, self.DOI)
  def get_absolute_url(self):
    return reverse('study_detail', args=[str(self.title)])

class CountData(models.Model):
  def directory_path(instance, filename):
    return 'count_data/{0}/{1}.csv'.format(instance.study.pk, instance.name)

  name = models.CharField(max_length=50, unique=True)
  study = models.ForeignKey(Study, to_field='DOI', on_delete=models.CASCADE)
  gene_count = models.FileField(upload_to=directory_path, validators=[FileExtensionValidator(allowed_extensions=['csv', 'tsv'])])
  class Meta:
    verbose_name = 'Count Data'
    verbose_name_plural = 'Count Data'
  def __str__(self):
    return self.name
  def get_absolute_url(self):
    return reverse('count_data_detail', args=[str(self.study.title), str(self.name)])

kernels = (
  ("RBF", "RBF"), 
  ("Linear", "Linear"), 
  ("Polynomial", "Poly"), 
  ("Sigmoid", "Sigmoid")
)

C_values = (
  ("1000", 1000), ("100", 100), ("10", 10), ("1", 1), ("0.1", 0.1), 
  ("0.01", 0.01), ("0.001", 0.001), ("1e-4", 1e-4), ("1e-5", 1e-5), 
  ("1e-6", 1e-6), ("1e-7", 1e-7), ("1e-8", 1e-8), ("1e-9", 1e-9), 
  ("1e-10", 1e-10)
)

gamma_values = (
  ("1000", 1000), ("100", 100), ("10", 10), ("1", 1), ("0.1", 0.1), 
  ("0.01", 0.01), ("0.001", 0.001), ("1e-4", 1e-4), ("1e-5", 1e-5), 
  ("1e-6", 1e-6), ("1e-7", 1e-7), ("1e-8", 1e-8), ("1e-9", 1e-9), ("1e-10", 1e-10)
)

def SVM_directory_path(instance, filename):
    return 'models/SVM/{0}/{1}.sav'.format(instance.count_data.study.id, instance.model_name)

class SVMModel(models.Model):
  model_name = models.CharField(max_length=50, unique=True)
  description = models.TextField()
  count_data = models.ForeignKey(CountData, to_field='name', on_delete=models.CASCADE)
  kernel = models.CharField(max_length=10, choices=kernels, verbose_name="Kernel")
  C = models.CharField(max_length=5, choices=C_values, blank=True)
  gamma = models.CharField(max_length=5, choices=gamma_values, blank=True)
  model_file = models.FileField(upload_to=SVM_directory_path, validators=[FileExtensionValidator(allowed_extensions=['sav'])])

  class Meta:
    verbose_name = 'Support Vector Machine model'
    verbose_name_plural = 'Support Vector Machine models'
  def __str__(self):
    return self.model_name
  def get_absolute_url(self):
    return reverse('svm_model_detail', args=[str(self.model_name)])

criteria = (
  ('Gini', 'Gini'), ('Entropy', 'Entropy')
  )

def RF_directory_path(instance, filename):
    return 'models/RF/{0}/{1}.sav'.format(instance.count_data.study.id, instance.model_name)

class RFModel(models.Model):
  model_name = models.CharField(max_length=50, unique=True)
  description = models.TextField()
  count_data = models.ForeignKey(CountData, to_field='name', on_delete=models.CASCADE)
  n_estimators = models.CharField(max_length=10, verbose_name="NumberOfEstimators", blank=True)
  max_depth = models.CharField(max_length=10, verbose_name="MaxDepth", blank=True)
  criterion = models.CharField(max_length=7, choices=criteria, verbose_name="Criterion")
  bootstrap = models.CharField(max_length=5, choices=(('True', 'True'), ('False', 'False')), verbose_name="Bootstrap")
  model_file = models.FileField(upload_to=RF_directory_path, validators=[FileExtensionValidator(allowed_extensions=['sav'])])

  class Meta:
    verbose_name = 'Random Forest model'
    verbose_name_plural = 'Random Forest models'
  def __str__(self): 
    return self.model_name
  def get_absolute_url(self):
    return reverse('rf_model_detail', args=[str(self.model_name)])

sexes = (
  ('M', 'Male'),
  ('F', 'Female')
)

class Sample(models.Model):
  count_data = models.ForeignKey(CountData, to_field='name', on_delete=models.CASCADE)
  sample_ID = models.CharField(max_length=20, verbose_name='SampleID', unique=True, primary_key=True)
  sample_source = models.CharField(max_length=50, verbose_name='Source')
  brain_region = models.CharField(max_length=50, verbose_name='Tissue')
  RIN = models.CharField(max_length=2, blank=True)
  diagnosis = models.ForeignKey(Disease, default=None, to_field='abbreviation', on_delete=models.CASCADE, verbose_name='Diagnosis', null=True, blank=True)
  sex = models.CharField(max_length=1, choices=sexes, verbose_name='Sex')
  age_at_death = models.CharField(max_length=3, null=True, verbose_name='AgeAtDeath')  
  ApoE = models.CharField(max_length=2, blank=True)
  PMI = models.CharField(max_length=2, blank=True)

  class Meta:
    verbose_name = 'Sample'
    verbose_name_plural = 'Samples'
    ordering = ['sample_ID']
  def __str__(self):
    return self.sample_ID
  def get_absolute_url(self):
    return reverse('sample_detail', args=[str(self.count_data.study.title), str(self.count_data.name), str(self.sample_ID)])

class Gene(models.Model):
  gene_id = models.CharField(max_length=16, verbose_name='Source')
  gene_description = models.CharField(max_length=200, verbose_name='Source', blank=True)
  gene_name = models.CharField(max_length=50, verbose_name='Source', blank=True)
  gene_type = models.CharField(max_length=50, verbose_name='Source', blank=True)

  class Meta:
    verbose_name = 'Gene'
    verbose_name_plural = 'Genes'
    ordering = ['gene_id']
  def __str__(self):
    return self.gene_id

application/core/forms.py
from django import forms

application/core/templates/search_templates/search_disease.html
{% include "base_generic.html" %}
{% load i18n %}
{% load account socialaccount %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_messages %}
<head>
<style>
#left {
  width: 500px;
  float: left;
  font-size: 100%;
  margin-bottom: 5px;
}
#right {
  margin-left: 500px;
  font-size: 100%;
  margin-bottom: 5px;
  }
.clear {
  clear: both;
}
</style>
</head>

{% block content %}
  <div class="container">
    <div style="margin-top:20px">
      <div class="text-center">
        <!-- HEADER -->
        <h1 style="font-size:650%;">AGED</h1>
        <h3>Analysis of Gene Expression in Dementia</h3> <br/><br/><br/><br/> 
        <div id="left">
          <h2><a href="javascript:history.go(-1);" style="margin-left:-15em;"><<</a></h2>
        </div>
        <div id="right">
        </div>
        <br/><br/><br/>
        <hr><br/><br/><br/><br/>
        <!-- CONTENT -->
        <form method="GET" action={% url 'search_disease' %} class="navbar-form">
          <div class="form-group">
            <label class="control-label" for="search-field">
            <i class="glyphicon glyphicon-search"></i></label>
            <input type="text" value="{{ request.GET.q }}" name="q" class="form-control search-field" placeholder="Search..." id="search-field" />
          </div>
        </form>
        <br/>
        <h1>Disease Library</h1>
        <br/><br/>
        <a href="/diseases/create">{% buttons submit='Create Disease'%}{% endbuttons %}</a> 
        <br/><br/><br/>
      </div>
      <!-- DISEASE LIST -->
      {% if diseases %}   
        <ul style="display:table; margin:0 auto;">
        {% for disease in diseases %}
            <div id="left">
              <a href="{{ disease.get_absolute_url }}">{{ disease.name }} ({{disease.abbreviation}})</a>
            </div>
            <div id="right">
              <a href="{{ disease.get_absolute_url }}/update">{% bootstrap_button "Update" size="xs" button_type="submit" button_class="btn-primary" %}</a>
              <a href="{{ disease.get_absolute_url }}/confirm_delete">{% bootstrap_button "Delete" size="xs" button_type="submit" button_class="btn-danger" %}</a>
            </div>
        {% endfor %}
        </ul>
      {% else %}
      <div class="text-center">
        <h4>There are no matching diseases.</h4>
      </div>
      {% endif %}
      <br/>
      <div class="text-center">
      <!-- PAGINATION -->
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              <span class="page-current">
                <h4>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</h4>
              </span>
              {% if page_obj.has_previous %}
                <h3><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><<</a></h3>
                <br/>
              {% endif %}
              {% if page_obj.has_next %}
                <h3><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">>></a></h3>
              {% endif %}
            </span>
          </div>
        {% endif %}
      {% endblock %}   
      <br/><br/> 
      </div>
      <hr> 
    </div>
  </div>
{% endblock %}

application/core/templates/search_templates/search_sample.html
{% include "base_generic.html" %}
{% load i18n %}
{% load account socialaccount %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}
  <div class="container">
    <div style="margin-top:20px">
      <div class="text-center">
        <!-- HEADER -->
        <h1 style="font-size:650%;">AGED</h1>
        <h3>Analysis of Gene Expression in Dementia</h3> <br/><br/><br/><br/> 
        <div id="left">
          <h2><a href="javascript:history.go(-1);" style="margin-left:-15em;"><<</a></h2>
        </div>
        <div id="right">
        </div>
        <br/><br/><br/>
        <hr><br/><br/><br/><br/>
        <!-- CONTENT -->
        <form method="GET" action={% url 'search_sample' %} class="navbar-form">
          <div class="form-group">
              <label class="control-label" for="search-field">
              <i class="glyphicon glyphicon-search"></i></label>
              <input type="text" value="{{ request.GET.q }}" name="q" class="form-control search-field" placeholder="Search..." id="search-field" />
          </div>
        </form>
        <br/>
        <h1>Sample List</h1>
        <br/><br/>
        <a href="{% url 'import_sample' title=title name=name %}"><button>Import Sample Set</button></a>
        <br/><br/><br/>
        </div>
        <!-- SAMPLE LIST -->
        {% if sample_list %}
        <div style="display:table; margin:0 auto;">
          {% for sample in samples %}
            <a href="{{ sample.get_absolute_url }}">{{ sample.sample_ID }}</a>
          {% endfor %}
        </div>
        {% else %}
          <h4>There are no matching samples.</h4>
        {% endif %}
      <br/>
      <div class="text-center">
        <!-- PAGINATION -->
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              <span class="page-current">
                <h4>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</h4>
              </span>
              {% if page_obj.has_previous %}
                <h3><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><<</a></h3>
                <br/>
              {% endif %}
              {% if page_obj.has_next %}
                <h3><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">>></a></h3>
              {% endif %}
            </span>
          </div>
        {% endif %}
      {% endblock %}
      <br/><br/> 
      </div>
      <hr>
    </div>
  </div>
{% endblock %}

application/core/templates/search_templates/search_study.html
{% include "base_generic.html" %}
{% load i18n %}
{% load account socialaccount %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_messages %}
<head>
<style>
#left {
  width: 600px;
  float: left;
  font-size: 100%;
  margin-bottom: 5px;
}
#right {
  margin-left: 700px;
  font-size: 100%;
  margin-bottom: 5px;
  }
.clear {
  clear: both;
}
</style>
</head>

{% block content %}
  <div class="container">
    <div style="margin-top:20px">
      <div class="text-center">
        <!-- HEADER -->
        <h1 style="font-size:650%;">AGED</h1>
        <h3>Analysis of Gene Expression in Dementia</h3> <br/><br/><br/><br/>
        <div id="left">
          <h2><a href="javascript:history.go(-1);" style="margin-left:-15em;"><<</a></h2>
        </div>
        <div id="right">
        </div>
        <br/><br/><br/>
        <hr><br/><br/><br/><br/>
        <!-- CONTENT -->
        <form method="GET" action={% url 'search_study' %} class="navbar-form">
          <div class="form-group">
            <label class="control-label" for="search-field">
            <i class="glyphicon glyphicon-search"></i></label>
            <input type="text" value="{{ request.GET.q }}" name="q" class="form-control search-field" placeholder="Search..." id="search-field" />
          </div>
        </form>
        <br/>
        <h1>Study Library</h1>
        <br/><br/>
        <a href="/studies/create"><button>Create Study</button></a>
        <br/><br/><br/>
      </div>
      <!-- STUDIES -->
      {% if studies %}
      <ul style="display:table; margin:0 auto;">
        {% for study in studies %}
          <div id="left"><a href="{{ study.get_absolute_url }}">{{ study.title }}</a></div>
          <div id="right"><a href="{{ study.get_absolute_url }}/update"><button>Update</button></a> <a href="{{ study.get_absolute_url }}/confirm_delete"><button>Delete</button></a></div>
        {% endfor %}
      </ul>
      {% else %}
      <div class="text-center">
        <h3>There are no matching studies.</h3>
      </div>   
      {% endif %} 
      <br/>
      <div class="text-center">
      <!-- PAGINATION -->
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              <span class="page-current">
                <h4>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</h4>
              </span>
              {% if page_obj.has_previous %}
                <h3><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><<</a></h3>
                <br/>
              {% endif %}
              {% if page_obj.has_next %}
                <h3><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">>></a></h3>
              {% endif %}
            </span>
          </div>
        {% endif %}
      {% endblock %}    
      <br/><br/> 
      </div>
      <hr> 
    </div>
  </div>
{% endblock %}